using System;
using System.Collections;
using System.Collections.Generic;
using InventorySystem;
using UnityEngine;
using UnityEngine.Tilemaps;


public class Resource : MonoBehaviour
{
    public int resourceID = -1; // if the resource is related to an item, resourceID should be the same as the itemID of the related item
    
    [NonSerialized]
    public ResourceDefinition resourceDef = null;

    [NonSerialized]
    public TileInfo tileInfo = null; // The tile on which this resource is located. This will be set when the resource is generated.

    public int currentGrowthStageIndex = 0;

    public int growthTimeCounter = 0;   // Counter for tracking time spent in the current growth stage. Time is measured in game minutes.

    public Dictionary<ItemType, int> gatheringActionCounter = new Dictionary<ItemType, int>(); // Key: the type of the tool used for gathering; Value: the number of actions already performed using that tool

    public Action<GameObject> onBeingGathered; 
    public Action<GameObject> onFinishedGathering; 
    [SerializeField] private SpriteRenderer spriteForAnimation;

    [SerializeField] private BoxCollider2D boxCollider;

    [SerializeField] private float finishedGatheringDelay = 0.0f; 

    public void Awake()
    {

        if(spriteForAnimation == null)
        {
            spriteForAnimation = GetComponent<SpriteRenderer>();
        }
    }

    public void Start()
    {
        // For resources that are placed in the scene manually by the designer, we need to initialize their resourceDef and tileInfo in the Start method. For resources that are generated by the game (e.g. tree saplings generated by a tree resource), their resourceDef and tileInfo will be initialized in the Initialize method called right after they are generated.
        if(tileInfo == null)
        {
            tileInfo = GameMapSubsystem.Instance.GetTileInfoByWorldPos(transform.position);
        }
        
        if(resourceDef == null && resourceID != -1)
        {
            resourceDef = ResourceSubsystem.Instance.GetResourceDefinition(resourceID);
            Initialize(resourceID, 0, 0);
        }
    }

    public void SetTileInfo(TileInfo tileInfo)
    {
        this.tileInfo = tileInfo;
    }

    public void OnDestroy()
    {
        if(ResourceSubsystem.Instance != null)
        {
            ResourceSubsystem.Instance.UnregisterResource(this);
        }
    }

    public void Initialize(int resourceID, int growthStageIndex, int grownTime)
    {
        // Set the resource ID & definition
        this.resourceID = resourceID;
        resourceDef = ResourceSubsystem.Instance.GetResourceDefinition(resourceID);

        // Get the tile info
        tileInfo = GameMapSubsystem.Instance.GetTileInfoByWorldPos(transform.position);

        // Set the collider based on the resource definition
        if(resourceDef.hasCollision)
        {
            boxCollider.isTrigger = false;
        }
        else
        {
            boxCollider.isTrigger = true;
        }
        boxCollider.size = resourceDef.colliderSize;

        // TODO: by this logic, the game wont remember the gathering progress after the player exits the game and reloads, which is not ideal. We should consider saving and loading the gathering progress as well in the future.
        foreach (GatheringRequirement requirement in resourceDef.gatheringRequirements)
        {
            gatheringActionCounter[requirement.requiredToolType] = 0;
        }

        currentGrowthStageIndex = growthStageIndex;
        this.growthTimeCounter = grownTime;

        if(currentGrowthStageIndex < resourceDef.growthStages.Count)
        {
            spriteForAnimation.sprite = resourceDef.growthStages[currentGrowthStageIndex].stageSprite;
        }

        ResourceSubsystem.Instance.RegisterResource(this);
    }
    public void Grow(int passedMinutes)
    {   

        // Check if the land has been watered. If not, the CROP will not grow.
        if(!tileInfo.isWatered && resourceDef.resourceType == ResourceType.Crop)
        {   
            return;
        }
        growthTimeCounter += passedMinutes;

        // TODO: need to consider the case when the resource can be gathered multiple times and has regrowth time. In that case, after the resource is gathered, it will go back to the previous growth stage and start regrowing from there. So we need to make sure the growth logic can handle this situation correctly.
        // A better way to make this logic may be to separate the ripe resource and the unripe resource into two different prefabs
        // so that we can directly switch the prefab when the resource becomes ripe, instead of trying to change the sprite of the same prefab.
        
        while (growthTimeCounter >= resourceDef.growthStages[currentGrowthStageIndex].timeToNextStage)
        {
            growthTimeCounter -= resourceDef.growthStages[currentGrowthStageIndex].timeToNextStage;
            currentGrowthStageIndex++;

            if (currentGrowthStageIndex >= resourceDef.growthStages.Count)
            {
                currentGrowthStageIndex = resourceDef.growthStages.Count - 1;
                
                // Only resource that cannot be gathered multiple times will spawn the ripe prefab on becoming ripe, because for resources that can be gathered multiple times, they will spawn the "after gathering" prefab when they are gathered, and they will not change their appearance when they become ripe, so there is no need to spawn a new prefab when they become ripe. But for resources that cannot be gathered multiple times, they will change their appearance when they become ripe, so we need to spawn a new prefab for the ripe stage if there is any assigned in the resource definition.
                if(!resourceDef.canBeGatheredMultipleTimes)
                {
                    // On becoming ripe, spawn the ripe prefab if there is any
                    SpawnResourcePrefabIfAnyAndDestroySelf(ResourcePrefabType.OnRipe);
                }

                break;
            }
        }

        // Update the sprite based on the current growth stage
        spriteForAnimation.sprite = resourceDef.growthStages[currentGrowthStageIndex].stageSprite;
    }

    private void SpawnResourcePrefabIfAnyAndDestroySelf(ResourcePrefabType type)
    {
        foreach(ResourcePrefabInfo prefabInfo in resourceDef.generatedObjectPrefabs)
        {
            if(prefabInfo.prefabType == type)
            {
                ResourceDefinition prefabResourceDef = prefabInfo.resourceID != -1 ? ResourceSubsystem.Instance.GetResourceDefinition(prefabInfo.resourceID) : null;

                if(prefabInfo.resourceID == -1)
                {
                    Debug.LogWarning($"Prefab for resource {gameObject.name} with prefab type {type} does not have a valid resourceID. It is recommended to assign a valid resourceID to the prefab so that the prefab can have the correct ResourceDefinition and be properly registered in the ResourceSubsystem.");
                }

                ResourceSubsystem.Instance.GenerateResource(tileInfo, prefabResourceDef, 0, 0);
                Destroy(gameObject);

                // TODO: maybe there will be mutiple prefabs with the same prefab type in the resource definition in the future, in that case we need to consider how to determine which prefab to spawn. 
                // For example, for a crop resource, we may want to spawn different ripe prefabs based on the season or other factors. For now we will just spawn the first prefab we find with the matching prefab type.
                break;
            }
        }

        // In case there is no prefab to spawn, we will just keep the current resource object as it is if it becomes ripe, or destroy the resource object if it is gathered, depending on the prefab type. This is to make sure the resource object can be properly removed from the game world when it is gathered, even if there is no prefab assigned for the AfterGathering type.
        if(type == ResourcePrefabType.AfterGathering)
        {
            Destroy(gameObject);
        }
        
    }

    // Gathering logic:
    public void BeingGathered(GameObject gatherer, ItemDefinition toolUsed)
    {
        onBeingGathered?.Invoke(gatherer);

        if(gatheringActionCounter.ContainsKey(toolUsed.itemType))
        {
            Debug.Log($"Gathering resource {gameObject.name} using {toolUsed.itemName}. Current action count: {gatheringActionCounter[toolUsed.itemType]}");

            gatheringActionCounter[toolUsed.itemType]++;
            GatheringRequirement requirement = resourceDef.gatheringRequirements.Find(r => r.requiredToolType == toolUsed.itemType);
            
            if(requirement != null && gatheringActionCounter[toolUsed.itemType] >= requirement.requiredActionCount)
            {
                Debug.Log($"Finished gathering resource {gameObject.name} using {toolUsed.itemName}!");
                StartCoroutine(FinishedGathering(gatherer, requirement.canGenerateProduct));
            }
        }
    }


    public IEnumerator FinishedGathering(GameObject gatherer, bool generateProducts)
    {
        // TODO: play gathering completion animation and sound effects.

        // Generate products based on the production info in the resource definition. We can consider adding some randomness to the produced item count in the future to make it more interesting.

        onFinishedGathering?.Invoke(gatherer);

        yield return new WaitForSeconds(finishedGatheringDelay); // Wait for the animation to finish

        if(generateProducts)
        {
            GenerateProducts(gatherer.GetComponent<PlayerController>(), currentGrowthStageIndex);
        }        
        

        if(resourceDef.canBeGatheredMultipleTimes)
        {
            // If the resource can be gathered multiple times, we will reset the growth stage to the previous stage (or the first stage if there is no previous stage), and reset the growth time counter as well, so that the resource can start regrowing again.
            currentGrowthStageIndex = Mathf.Max(0, currentGrowthStageIndex - 1);
            growthTimeCounter = 0;

            // Update the sprite based on the new growth stage
            spriteForAnimation.sprite = resourceDef.growthStages[currentGrowthStageIndex].stageSprite;
        }
        else
        {
            SpawnResourcePrefabIfAnyAndDestroySelf(ResourcePrefabType.AfterGathering);
        }
    }

    private void GenerateProducts(PlayerController player, int growthStageIndex)
    {
        if(player == null)
        {
            Debug.LogError("Player reference is null in GenerateProducts method. Cannot generate products without a valid player reference.");
            return;
        }

        if(growthStageIndex == resourceDef.growthStages.Count - 1 || resourceDef.growthStages.Count == 0)
        {
            // means the last stage (ripe stage), we will set the growthStageIndex in production info to -1 to indicate that the product can be generated at the ripe stage.
            growthStageIndex = -1; 
        }

        foreach(ProductionInfo productionInfo in resourceDef.productionInfos)
        {
            if(productionInfo.growthStageIndex == growthStageIndex)
            {
                int itemCount = UnityEngine.Random.Range(productionInfo.producedItemMinCount, productionInfo.producedItemMaxCount + 1);

                if(itemCount > 0)
                {
                    if(resourceDef.dropProductsOnGround)
                    {
                        // TODO: randomly scatter the produced items around the resource position instead of spawning them all at the same position to make it look more natural.
                        GameMapSubsystem.Instance.SpawnDroppedItemInWorld(productionInfo.producedItemID, itemCount, transform.position);
                    }
                    else
                    {
                        // Add the produced items directly to the player's inventory. We need to make sure the player has enough inventory space to receive the produced items before we add them to the inventory.
                        //  If the player does not have enough inventory space, we will drop the produced items on the ground instead to avoid losing the produced items.
                        InventoryComponent inventory = player.inventoryComponent;
                        int remainder = inventory.TryAddItem(productionInfo.producedItemID, itemCount);

                        if(remainder > 0)
                        {
                            GameMapSubsystem.Instance.SpawnDroppedItemInWorld(productionInfo.producedItemID, remainder, transform.position);
                        }
                    }
                }
            }
        }
    }

}
